typography_spectrum: 0.25292530143633485
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6413818395230919
  lightness: 0.8735121020581573
  saturation: 0.7290898703504354
  rhythmicContrast: 0.7260457070078701
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4878277324605733
analytics:
  google: null
  facebook: null
  twitter: null
name: heart
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Heart
purpose: []
